CREATE TABLE Seller(
	SellerId int AUTO_INCREMENT NOT NULL,
	Email varchar(512) NOT NULL,
	EbayUser varchar(50) NOT NULL,
	Created datetime NOT NULL,
 CONSTRAINT PK_Seller PRIMARY KEY CLUSTERED 
(
	SellerId ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON PRIMARY
) ON PRIMARY
;
CREATE TABLE ProductStatus(
	ProductStatusId int AUTO_INCREMENT NOT NULL,
	Name varchar(50) NOT NULL,
	Created datetime NOT NULL,
 CONSTRAINT PK_ProductStatus PRIMARY KEY CLUSTERED 
(
	ProductStatusId ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON PRIMARY
) ON PRIMARY
;
CREATE TABLE Image(
	ImageId int AUTO_INCREMENT NOT NULL,
	ImagePath varchar(512) NOT NULL,
	Height int NOT NULL,
	Width int NOT NULL,
	Size int NOT NULL,
	Created datetime NOT NULL,
 CONSTRAINT PK_Image PRIMARY KEY CLUSTERED 
(
	ImageId ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON PRIMARY
) ON PRIMARY
;
CREATE TABLE Html(
	HtmlId int AUTO_INCREMENT NOT NULL,
	Name varchar(512) NOT NULL,
	Html varchar(max) NOT NULL,
	Created datetime NOT NULL,
 CONSTRAINT PK_Html PRIMARY KEY CLUSTERED 
(
	HtmlId ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON PRIMARY
) ON PRIMARY
;
CREATE TABLE Site(
	SiteId int AUTO_INCREMENT NOT NULL,
	Name varchar(512) NOT NULL,
	SellerId int NOT NULL,
	Created datetime NOT NULL,
 CONSTRAINT PK_Site PRIMARY KEY CLUSTERED 
(
	SiteId ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON PRIMARY
) ON PRIMARY
;
CREATE TABLE Product(
	ProductId int AUTO_INCREMENT NOT NULL,
	SiteId int NOT NULL,
	ProductStatusId int NOT NULL,
	Title varchar(512) NOT NULL,
	Created datetime NOT NULL,
 CONSTRAINT PK_Product PRIMARY KEY CLUSTERED 
(
	ProductId ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON PRIMARY
) ON PRIMARY
;
CREATE TABLE Page(
	PageId int AUTO_INCREMENT NOT NULL,
	SiteId int NOT NULL,
	Name varchar(512) NOT NULL,
	Title varchar(1024) NOT NULL,
	HtmlId int NOT NULL,
	Created datetime NOT NULL,
 CONSTRAINT PK_Page PRIMARY KEY CLUSTERED 
(
	PageId ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON PRIMARY
) ON PRIMARY
;
CREATE TABLE ProductListing(
	ProductId int NOT NULL,
	HtmlId int NOT NULL,
 CONSTRAINT PK_ProductListing PRIMARY KEY CLUSTERED 
(
	ProductId ASC,
	HtmlId ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON PRIMARY
) ON PRIMARY
;
CREATE TABLE ProductImage(
	ProductId int NOT NULL,
	ImageId int NOT NULL,
	IsPrimary bit NOT NULL,
 CONSTRAINT PK_ProductImage PRIMARY KEY CLUSTERED 
(
	ProductId ASC,
	ImageId ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON PRIMARY
) ON PRIMARY
;
CREATE TABLE ProductDescription(
	ProductId int NOT NULL,
	HtmlId int NOT NULL,
 CONSTRAINT PK_ProductDescription PRIMARY KEY CLUSTERED 
(
	ProductId ASC,
	HtmlId ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON PRIMARY
) ON PRIMARY
;
CREATE TABLE ProductAttribute(
	ProductAttributeId int AUTO_INCREMENT NOT NULL,
	ProductId int NOT NULL,
	Name varchar(1024) NOT NULL,
	Value varchar(max) NOT NULL,
	IsGroup bit NOT NULL,
	Created datetime NOT NULL,
 CONSTRAINT PK_ProductAttribute PRIMARY KEY CLUSTERED 
(
	ProductAttributeId ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON PRIMARY
) ON PRIMARY
;
ALTER TABLE Seller ADD  CONSTRAINT DF_Seller_Created  DEFAULT (CURRENT_TIMESTAMP) FOR Created
;
ALTER TABLE ProductStatus ADD  CONSTRAINT DF_ProductStatus_Created  DEFAULT (CURRENT_TIMESTAMP) FOR Created
;
ALTER TABLE Image ADD  CONSTRAINT DF_ProductImage_Created  DEFAULT (CURRENT_TIMESTAMP) FOR Created
;
ALTER TABLE Html ADD  CONSTRAINT DF_Html_Created  DEFAULT (CURRENT_TIMESTAMP) FOR Created
;
ALTER TABLE Site ADD  CONSTRAINT DF_Site_Created  DEFAULT (CURRENT_TIMESTAMP) FOR Created
;
ALTER TABLE Product ADD  CONSTRAINT DF_Product_Created  DEFAULT (CURRENT_TIMESTAMP) FOR Created
;
ALTER TABLE Page ADD  CONSTRAINT DF_Page_Created  DEFAULT (CURRENT_TIMESTAMP) FOR Created
;
ALTER TABLE ProductImage ADD  CONSTRAINT DF_ProductImage_IsPrimary  DEFAULT 0 FOR IsPrimary
;
ALTER TABLE ProductAttribute ADD  CONSTRAINT DF_Attribute_Value  DEFAULT ('') FOR Value
;
ALTER TABLE ProductAttribute ADD  CONSTRAINT DF_Attribute_IsGroup  DEFAULT 0 FOR IsGroup
;
ALTER TABLE ProductAttribute ADD  CONSTRAINT DF_Attribute_Created  DEFAULT (CURRENT_TIMESTAMP) FOR Created
;
ALTER TABLE Site  WITH CHECK ADD  CONSTRAINT FK_Site_Seller FOREIGN KEY(SellerId)
REFERENCES Seller (SellerId)
;
ALTER TABLE Site CHECK CONSTRAINT FK_Site_Seller
;
ALTER TABLE Product  WITH CHECK ADD  CONSTRAINT FK_Product_ProductStatus FOREIGN KEY(ProductStatusId)
REFERENCES ProductStatus (ProductStatusId)
;
ALTER TABLE Product CHECK CONSTRAINT FK_Product_ProductStatus
;
ALTER TABLE Product  WITH CHECK ADD  CONSTRAINT FK_Product_Site FOREIGN KEY(SiteId)
REFERENCES Site (SiteId)
;
ALTER TABLE Product CHECK CONSTRAINT FK_Product_Site
;
ALTER TABLE Page  WITH CHECK ADD  CONSTRAINT FK_Page_Html FOREIGN KEY(HtmlId)
REFERENCES Html (HtmlId)
;
ALTER TABLE Page CHECK CONSTRAINT FK_Page_Html
;
ALTER TABLE Page  WITH CHECK ADD  CONSTRAINT FK_Page_Site FOREIGN KEY(SiteId)
REFERENCES Site (SiteId)
;
ALTER TABLE Page CHECK CONSTRAINT FK_Page_Site
;
ALTER TABLE ProductListing  WITH CHECK ADD  CONSTRAINT FK_ProductListing_Html FOREIGN KEY(HtmlId)
REFERENCES Html (HtmlId)
;
ALTER TABLE ProductListing CHECK CONSTRAINT FK_ProductListing_Html
;
ALTER TABLE ProductListing  WITH CHECK ADD  CONSTRAINT FK_ProductListing_Product FOREIGN KEY(ProductId)
REFERENCES Product (ProductId)
;
ALTER TABLE ProductListing CHECK CONSTRAINT FK_ProductListing_Product
;
ALTER TABLE ProductImage  WITH CHECK ADD  CONSTRAINT FK_ProductImage_Image FOREIGN KEY(ImageId)
REFERENCES Image (ImageId)
;
ALTER TABLE ProductImage CHECK CONSTRAINT FK_ProductImage_Image
;
ALTER TABLE ProductImage  WITH CHECK ADD  CONSTRAINT FK_ProductImage_Product FOREIGN KEY(ProductId)
REFERENCES Product (ProductId)
;
ALTER TABLE ProductImage CHECK CONSTRAINT FK_ProductImage_Product
;
ALTER TABLE ProductDescription  WITH CHECK ADD  CONSTRAINT FK_ProductDescription_Html FOREIGN KEY(HtmlId)
REFERENCES Html (HtmlId)
;
ALTER TABLE ProductDescription CHECK CONSTRAINT FK_ProductDescription_Html
;
ALTER TABLE ProductDescription  WITH CHECK ADD  CONSTRAINT FK_ProductDescription_Product FOREIGN KEY(ProductId)
REFERENCES Product (ProductId)
;
ALTER TABLE ProductDescription CHECK CONSTRAINT FK_ProductDescription_Product
;
ALTER TABLE ProductAttribute  WITH CHECK ADD  CONSTRAINT FK_ProductAttribute_Product FOREIGN KEY(ProductId)
REFERENCES Product (ProductId)
;
ALTER TABLE ProductAttribute CHECK CONSTRAINT FK_ProductAttribute_Product
;
